/* The following code was generated by JFlex 1.6.0 */

package Analisis;
import Analisis.sym.*;
import java_cup.runtime.Symbol;
import Errores.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.0
 * from the specification file <tt>C:/Users/Kristhal/Documents/NetBeansProjects/[Compi2]Proyecto1_201314655/src/Analisis/scannerHaskell.jflex</tt>
 */
public class lexicoHanskell implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\70\1\70\1\71\1\70\1\70\22\0\1\32\1\10\1\1"+
    "\1\14\1\13\1\14\1\31\1\6\1\61\1\62\1\30\1\27\1\21"+
    "\1\20\1\5\1\65\12\2\1\67\1\24\1\22\1\15\1\23\1\14"+
    "\1\14\1\37\1\7\1\36\1\44\1\34\1\57\1\55\1\56\1\47"+
    "\2\7\1\33\1\45\1\50\1\53\1\52\1\60\1\41\1\43\1\35"+
    "\1\40\1\54\1\7\1\51\2\7\1\25\1\14\1\26\1\14\1\4"+
    "\1\0\1\37\1\7\1\36\1\44\1\34\1\57\1\55\1\56\1\47"+
    "\2\7\1\33\1\45\1\50\1\53\1\52\1\60\1\41\1\43\1\35"+
    "\1\40\1\54\1\7\1\51\2\7\1\63\1\66\1\64\1\14\6\0"+
    "\1\71\44\0\1\12\1\0\1\12\4\0\1\3\5\0\1\12\2\0"+
    "\1\12\2\0\1\12\1\0\1\12\2\0\1\11\1\16\154\0\2\46"+
    "\115\0\1\42\u1e98\0\1\3\10\0\1\17\6\0\1\71\1\71\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\2\1\1\2\1\3\2\1\1\4\1\5\1\6"+
    "\1\7\1\10\1\11\1\12\1\13\1\14\1\15\1\16"+
    "\1\1\1\17\6\3\1\1\3\3\1\1\2\3\1\20"+
    "\1\21\1\22\1\23\1\24\1\1\1\25\1\0\1\26"+
    "\2\0\1\27\6\0\1\30\1\31\1\32\1\33\1\34"+
    "\1\35\1\36\5\3\1\0\2\3\1\0\3\3\1\0"+
    "\1\3\1\0\1\37\1\3\1\37\2\3\1\40\1\41"+
    "\3\0\1\42\1\3\1\0\1\3\1\43\2\3\1\0"+
    "\1\3\2\44\1\3\1\0\1\45\1\3\1\45\1\3"+
    "\1\0\1\3\1\46\2\47\1\0\1\3\1\50\1\3"+
    "\3\0\1\3\2\51\1\52\1\3\2\53\1\3\2\54"+
    "\1\55\2\56\2\57\1\3\1\0\1\60\1\61\4\3"+
    "\1\62\1\63\1\3\2\64\2\3\1\65\1\66";

  private static int [] zzUnpackAction() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\72\0\164\0\256\0\350\0\u0122\0\u015c\0\72"+
    "\0\u0196\0\72\0\72\0\u01d0\0\u020a\0\72\0\72\0\72"+
    "\0\u0244\0\72\0\u027e\0\u02b8\0\u02f2\0\u032c\0\u0366\0\u03a0"+
    "\0\u03da\0\u0414\0\u044e\0\u0488\0\u04c2\0\u04fc\0\u0536\0\u0570"+
    "\0\u05aa\0\72\0\72\0\72\0\72\0\72\0\u05e4\0\72"+
    "\0\164\0\72\0\u061e\0\u0658\0\72\0\u0692\0\u06cc\0\u0706"+
    "\0\u0740\0\u077a\0\u07b4\0\72\0\72\0\72\0\72\0\72"+
    "\0\72\0\72\0\u07ee\0\u0828\0\u0862\0\u089c\0\u08d6\0\u0910"+
    "\0\u094a\0\u0984\0\u09be\0\u09f8\0\u0a32\0\u0a6c\0\u0aa6\0\u0ae0"+
    "\0\u0b1a\0\72\0\u0b54\0\350\0\u0b8e\0\u0bc8\0\72\0\u061e"+
    "\0\u0c02\0\u0c3c\0\u0c76\0\350\0\u0cb0\0\u0cea\0\u0d24\0\350"+
    "\0\u0d5e\0\u0d98\0\u0dd2\0\u0e0c\0\72\0\350\0\u0e46\0\u0e80"+
    "\0\72\0\u0eba\0\350\0\u0ef4\0\u0f2e\0\u0f68\0\350\0\72"+
    "\0\350\0\u0fa2\0\u0fdc\0\350\0\u1016\0\u1050\0\u108a\0\u10c4"+
    "\0\u10fe\0\72\0\350\0\350\0\u1138\0\72\0\350\0\u1172"+
    "\0\72\0\350\0\350\0\72\0\350\0\72\0\350\0\u11ac"+
    "\0\u11e6\0\72\0\72\0\u1220\0\u125a\0\u1294\0\u12ce\0\72"+
    "\0\350\0\u1308\0\72\0\350\0\u1342\0\u137c\0\350\0\350";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\2\2\1\6\1\5\1\7"+
    "\2\2\1\10\1\2\1\11\1\5\1\2\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\1\5\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\2\5\1\41"+
    "\6\5\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\24\73\0\1\51\1\52\70\51\2\0\1\4\2\0"+
    "\1\53\66\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\7\5\1\0\3\5\1\0\12\5\12\0\2\54\1\0"+
    "\2\54\1\55\2\54\1\56\1\0\3\54\1\57\1\0"+
    "\22\54\1\60\1\61\1\54\1\62\1\0\3\54\1\63"+
    "\6\54\21\0\1\64\4\0\1\65\71\0\1\66\71\0"+
    "\1\67\71\0\1\70\103\0\1\71\73\0\1\72\72\0"+
    "\1\24\35\0\1\24\3\0\3\5\2\0\1\5\6\0"+
    "\1\5\14\0\1\5\1\73\5\5\1\0\3\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\1\74\6\5\1\0\3\5\1\0\1\5\1\75\10\5"+
    "\13\0\3\5\2\0\1\5\6\0\1\5\14\0\7\5"+
    "\1\0\3\5\1\0\7\5\1\76\2\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\4\5\1\77\2\5"+
    "\1\0\3\5\1\0\12\5\13\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\7\5\1\100\1\101\2\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\1\5\1\102\5\5\1\0\3\5\1\0\12\5\51\0"+
    "\1\103\33\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\5\5\1\104\1\5\1\0\3\5\1\0\12\5\13\0"+
    "\3\5\2\0\1\5\6\0\1\5\14\0\1\5\1\105"+
    "\5\5\1\0\3\5\1\0\12\5\13\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\4\5\1\106\2\5\1\0"+
    "\3\5\1\107\1\110\11\5\56\0\1\111\11\0\1\112"+
    "\14\0\3\5\2\0\1\5\6\0\1\5\14\0\7\5"+
    "\1\0\2\5\1\113\1\0\10\5\1\114\1\5\13\0"+
    "\3\5\2\0\1\5\6\0\1\5\14\0\4\5\1\115"+
    "\1\5\1\116\1\0\3\5\1\0\12\5\77\0\1\117"+
    "\5\0\1\120\75\0\1\55\75\0\1\54\76\0\1\54"+
    "\132\0\1\121\17\0\1\55\51\0\1\121\17\0\1\55"+
    "\44\0\1\122\24\0\1\55\44\0\1\123\20\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\2\5\1\124\4\5"+
    "\1\0\3\5\1\0\1\5\1\125\10\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\7\5\1\126\1\127"+
    "\2\5\1\0\12\5\13\0\3\5\2\0\1\5\6\0"+
    "\1\5\14\0\7\5\1\0\1\5\1\130\1\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\1\5\1\131\5\5\1\0\3\5\1\0\12\5\13\0"+
    "\3\5\2\0\1\5\6\0\1\5\14\0\1\132\6\5"+
    "\1\133\1\134\2\5\1\0\12\5\47\0\1\135\35\0"+
    "\3\5\2\0\1\5\6\0\1\5\14\0\3\5\1\136"+
    "\3\5\1\0\3\5\1\0\12\5\13\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\7\5\1\0\3\5\1\0"+
    "\5\5\1\137\4\5\47\0\1\140\6\0\1\141\26\0"+
    "\3\5\2\0\1\5\6\0\1\5\14\0\3\5\1\142"+
    "\3\5\1\0\2\5\1\143\1\0\12\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\3\5\1\144\3\5"+
    "\1\145\1\146\2\5\1\0\12\5\13\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\7\5\1\0\3\5\1\0"+
    "\2\5\1\147\7\5\61\0\1\150\23\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\7\5\1\0\3\5\1\0"+
    "\1\5\1\151\10\5\63\0\1\152\21\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\7\5\1\0\3\5\1\0"+
    "\3\5\1\153\6\5\13\0\3\5\2\0\1\5\6\0"+
    "\1\5\14\0\6\5\1\154\1\0\3\5\1\0\12\5"+
    "\13\0\3\5\2\0\1\5\6\0\1\5\14\0\7\5"+
    "\1\0\3\5\1\0\4\5\1\155\5\5\52\0\1\156"+
    "\74\0\1\157\62\0\1\160\36\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\7\5\1\0\3\5\1\0\6\5"+
    "\1\161\3\5\45\0\1\162\37\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\1\5\1\163\5\5\1\0\3\5"+
    "\1\0\12\5\13\0\3\5\2\0\1\5\6\0\1\5"+
    "\14\0\7\5\1\0\3\5\1\0\1\5\1\164\10\5"+
    "\13\0\3\5\2\0\1\5\6\0\1\5\14\0\3\5"+
    "\1\165\3\5\1\0\3\5\1\0\12\5\45\0\1\166"+
    "\37\0\3\5\2\0\1\5\6\0\1\5\14\0\1\5"+
    "\1\167\5\5\1\0\3\5\1\0\12\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\1\5\1\170\5\5"+
    "\1\0\3\5\1\0\12\5\47\0\1\171\35\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\3\5\1\172\3\5"+
    "\1\0\3\5\1\0\12\5\13\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\3\5\1\173\3\5\1\0\3\5"+
    "\1\0\12\5\47\0\1\174\35\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\3\5\1\175\3\5\1\0\3\5"+
    "\1\0\12\5\52\0\1\176\32\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\6\5\1\177\1\0\3\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\7\5\1\0\1\5\1\200\1\5\1\0\12\5\46\0"+
    "\1\201\42\0\1\202\71\0\1\203\65\0\3\5\2\0"+
    "\1\5\6\0\1\5\14\0\2\5\1\204\4\5\1\0"+
    "\3\5\1\0\12\5\13\0\3\5\2\0\1\5\6\0"+
    "\1\5\14\0\5\5\1\205\1\5\1\0\3\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\6\5\1\206\1\0\3\5\1\0\12\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\5\5\1\207\1\5"+
    "\1\0\3\5\1\0\12\5\17\0\1\210\65\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\7\5\1\0\3\5"+
    "\1\0\7\5\1\211\2\5\13\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\1\212\6\5\1\0\3\5\1\0"+
    "\12\5\13\0\3\5\2\0\1\5\6\0\1\5\14\0"+
    "\7\5\1\213\1\214\2\5\1\0\12\5\13\0\3\5"+
    "\2\0\1\5\6\0\1\5\14\0\3\5\1\215\3\5"+
    "\1\0\3\5\1\0\12\5\13\0\3\5\2\0\1\5"+
    "\6\0\1\5\14\0\4\5\1\216\2\5\1\0\3\5"+
    "\1\0\12\5\13\0\3\5\2\0\1\5\6\0\1\5"+
    "\14\0\2\5\1\217\4\5\1\0\3\5\1\0\12\5"+
    "\13\0\3\5\2\0\1\5\6\0\1\5\14\0\6\5"+
    "\1\220\1\0\3\5\1\0\12\5\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5046];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\5\1\1\11\1\1\2\11\2\1\3\11"+
    "\1\1\1\11\17\1\5\11\1\1\1\11\1\0\1\11"+
    "\2\0\1\11\6\0\7\11\5\1\1\0\2\1\1\0"+
    "\3\1\1\0\1\1\1\0\1\11\4\1\1\11\1\1"+
    "\3\0\2\1\1\0\4\1\1\0\1\1\1\11\2\1"+
    "\1\0\1\11\3\1\1\0\2\1\1\11\1\1\1\0"+
    "\3\1\3\0\1\1\1\11\3\1\1\11\2\1\1\11"+
    "\2\1\1\11\1\1\1\11\2\1\1\0\2\11\4\1"+
    "\1\11\2\1\1\11\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[144];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
//VARIABLES Y METODOS DEL SCANNER EN JAVA
    private Errores err = Errores.getInstance();
    private void reportarError(int fila, int columna, String descError)
    {
        err.nuevoErrorLexico(fila, columna, descError);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public lexicoHanskell(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 272) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;           
    int totalRead = 0;
    while (totalRead < requested) {
      int numRead = zzReader.read(zzBuffer, zzEndRead + totalRead, requested - totalRead);
      if (numRead == -1) {
        break;
      }
      totalRead += numRead;
    }

    if (totalRead > 0) {
      zzEndRead += totalRead;
      if (totalRead == requested) { /* possibly more input available */
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      return false;
    }

    // totalRead = 0: End of stream
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          zzR = false;
          break;
        case '\r':
          yyline++;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
          }
          break;
        default:
          zzR = false;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 1: 
          { System.out.println("Error en el token: " + yytext() + "linea: "+ yyline);
                        reportarError((yyline+1), (yycolumn+1), "El token "+ yytext()+" no forma parte del lenguaje");
          }
        case 55: break;
        case 2: 
          { System.out.println("Entro numero");
                    return new Symbol(symH.numero, yyline, yycolumn, new String(yytext()));
          }
        case 56: break;
        case 3: 
          { System.out.println("Entro id");
                    return new Symbol(symH.identificador, yyline, yycolumn, new String(yytext()));
          }
        case 57: break;
        case 4: 
          { System.out.println("Entro $");
                    return new Symbol(symH.dolar, yyline, yycolumn, new String(yytext()));
          }
        case 58: break;
        case 5: 
          { System.out.println("Entro =");
                    return new Symbol(symH.igual, yyline, yycolumn, new String(yytext()));
          }
        case 59: break;
        case 6: 
          { System.out.println("Entro -");
                    return new Symbol(symH.menos, yyline, yycolumn, new String(yytext()));
          }
        case 60: break;
        case 7: 
          { System.out.println("Entro ,");
                    return new Symbol(symH.coma, yyline, yycolumn, new String(yytext()));
          }
        case 61: break;
        case 8: 
          { System.out.println("Entro <");
                    return new Symbol(symH.menor, yyline, yycolumn, new String(yytext()));
          }
        case 62: break;
        case 9: 
          { System.out.println("Entro >");
                    return new Symbol(symH.mayor, yyline, yycolumn, new String(yytext()));
          }
        case 63: break;
        case 10: 
          { System.out.println("Entro ;");
                    return new Symbol(symH.pyc, yyline, yycolumn, new String(yytext()));
          }
        case 64: break;
        case 11: 
          { System.out.println("Entro [");
                    return new Symbol(symH.cor_izq, yyline, yycolumn, new String(yytext()));
          }
        case 65: break;
        case 12: 
          { System.out.println("Entro ]");
                    return new Symbol(symH.cor_der, yyline, yycolumn, new String(yytext()));
          }
        case 66: break;
        case 13: 
          { System.out.println("Entro +");
                    return new Symbol(symH.mas, yyline, yycolumn, new String(yytext()));
          }
        case 67: break;
        case 14: 
          { System.out.println("Entro *");
                    return new Symbol(symH.por, yyline, yycolumn, new String(yytext()));
          }
        case 68: break;
        case 15: 
          { /* Se ignoran */
          }
        case 69: break;
        case 16: 
          { System.out.println("Entro (");
                    return new Symbol(symH.par_izq, yyline, yycolumn, new String(yytext()));
          }
        case 70: break;
        case 17: 
          { System.out.println("Entro )");
                    return new Symbol(symH.par_der, yyline, yycolumn, new String(yytext()));
          }
        case 71: break;
        case 18: 
          { System.out.println("Entro {");
                    return new Symbol(symH.llave_izq, yyline, yycolumn, new String(yytext()));
          }
        case 72: break;
        case 19: 
          { System.out.println("Entro }");
                    return new Symbol(symH.llave_der, yyline, yycolumn, new String(yytext()));
          }
        case 73: break;
        case 20: 
          { System.out.println("Entro /");
                    return new Symbol(symH.div, yyline, yycolumn, new String(yytext()));
          }
        case 74: break;
        case 21: 
          { System.out.println("Entro :");
                    return new Symbol(symH.dosp, yyline, yycolumn, new String(yytext()));
          }
        case 75: break;
        case 22: 
          { System.out.println("Entro texto");
                    return new Symbol(symH.texto, yyline, yycolumn, new String(yytext()));
          }
        case 76: break;
        case 23: 
          { System.out.println("Entro caracter");
                    return new Symbol(symH.caracter, yyline, yycolumn, new String(yytext()));
          }
        case 77: break;
        case 24: 
          { System.out.println("Entro !!");
                    return new Symbol(symH.dadmiracion, yyline, yycolumn, new String(yytext()));
          }
        case 78: break;
        case 25: 
          { System.out.println("Entro !=");
                    return new Symbol(symH.diferente, yyline, yycolumn, new String(yytext()));
          }
        case 79: break;
        case 26: 
          { System.out.println("Entro ==");
                    return new Symbol(symH.igualacion, yyline, yycolumn, new String(yytext()));
          }
        case 80: break;
        case 27: 
          { System.out.println("Entro <=");
                    return new Symbol(symH.menor_igual, yyline, yycolumn, new String(yytext()));
          }
        case 81: break;
        case 28: 
          { System.out.println("Entro >=");
                    return new Symbol(symH.mayor_igual, yyline, yycolumn, new String(yytext()));
          }
        case 82: break;
        case 29: 
          { System.out.println("Entro ++");
                    return new Symbol(symH.aumento, yyline, yycolumn, new String(yytext()));
          }
        case 83: break;
        case 30: 
          { System.out.println("Entro &&");
                    return new Symbol(symH.tkn_and, yyline, yycolumn, new String(yytext()));
          }
        case 84: break;
        case 31: 
          { System.out.println("Entro if");
                    return new Symbol(symH.tkn_if, yyline, yycolumn, new String(yytext()));
          }
        case 85: break;
        case 32: 
          { System.out.println("Entro ||");
                    return new Symbol(symH.tkn_or, yyline, yycolumn, new String(yytext()));
          }
        case 86: break;
        case 33: 
          { System.out.println("Entro decimal");
                    return new Symbol(symH.decimal, yyline, yycolumn, new String(yytext()));
          }
        case 87: break;
        case 34: 
          { System.out.println("Entro let");
                    return new Symbol(symH.tkn_let, yyline, yycolumn, new String(yytext()));
          }
        case 88: break;
        case 35: 
          { System.out.println("Entro end");
                    return new Symbol(symH.tkn_end, yyline, yycolumn, new String(yytext()));
          }
        case 89: break;
        case 36: 
          { System.out.println("Entro asc");
                    return new Symbol(symH.tkn_asc, yyline, yycolumn, new String(yytext()));
          }
        case 90: break;
        case 37: 
          { System.out.println("Entro sum");
                    return new Symbol(symH.tkn_sum, yyline, yycolumn, new String(yytext()));
          }
        case 91: break;
        case 38: 
          { System.out.println("Entro Max");
                    return new Symbol(symH.tkn_max, yyline, yycolumn, new String(yytext()));
          }
        case 92: break;
        case 39: 
          { System.out.println("Entro Min");
                    return new Symbol(symH.tkn_min, yyline, yycolumn, new String(yytext()));
          }
        case 93: break;
        case 40: 
          { System.out.println("Entro par");
                    return new Symbol(symH.tkn_par, yyline, yycolumn, new String(yytext()));
          }
        case 94: break;
        case 41: 
          { System.out.println("Entro else");
                    return new Symbol(symH.tkn_else, yyline, yycolumn, new String(yytext()));
          }
        case 95: break;
        case 42: 
          { System.out.println("Entro then");
                    return new Symbol(symH.tkn_then, yyline, yycolumn, new String(yytext()));
          }
        case 96: break;
        case 43: 
          { System.out.println("Entro case");
                    return new Symbol(symH.tkn_case, yyline, yycolumn, new String(yytext()));
          }
        case 97: break;
        case 44: 
          { System.out.println("Entro Succ");
                    return new Symbol(symH.tkn_succ, yyline, yycolumn, new String(yytext()));
          }
        case 98: break;
        case 45: 
          { System.out.println("Entro Decc");
                    return new Symbol(symH.tkn_decc, yyline, yycolumn, new String(yytext()));
          }
        case 99: break;
        case 46: 
          { System.out.println("Entro desc");
                    return new Symbol(symH.tkn_desc, yyline, yycolumn, new String(yytext()));
          }
        case 100: break;
        case 47: 
          { System.out.println("Entro impr");
                    return new Symbol(symH.tkn_impr, yyline, yycolumn, new String(yytext()));
          }
        case 101: break;
        case 48: 
          { System.out.println("Entro mod");
                    return new Symbol(symH.mod, yyline, yycolumn, new String(yytext()));
          }
        case 102: break;
        case 49: 
          { System.out.println("Entro pot");
                    return new Symbol(symH.potencia, yyline, yycolumn, new String(yytext()));
          }
        case 103: break;
        case 50: 
          { System.out.println("Entro sqrt");
                    return new Symbol(symH.sqrt, yyline, yycolumn, new String(yytext()));
          }
        case 104: break;
        case 51: 
          { System.out.println("Entro length");
                    return new Symbol(symH.tkn_length, yyline, yycolumn, new String(yytext()));
          }
        case 105: break;
        case 52: 
          { System.out.println("Entro revers");
                    return new Symbol(symH.tkn_revers, yyline, yycolumn, new String(yytext()));
          }
        case 106: break;
        case 53: 
          { System.out.println("Entro product");
                    return new Symbol(symH.tkn_product, yyline, yycolumn, new String(yytext()));
          }
        case 107: break;
        case 54: 
          { System.out.println("Entro Calcular");
                    return new Symbol(symH.tkn_calcular, yyline, yycolumn, new String(yytext()));
          }
        case 108: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(symH.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
