
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 22 20:55:49 CST 2017
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class symCSV {
  /* terminals */
  public static final int llave_izq = 7;
  public static final int coma = 9;
  public static final int llave_der = 8;
  public static final int finCadena = 11;
  public static final int decimal = 4;
  public static final int EOF = 0;
  public static final int texto = 3;
  public static final int cor_izq = 5;
  public static final int numero = 2;
  public static final int error = 1;
  public static final int cor_der = 6;
  public static final int salto = 10;
}

