
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Mar 20 10:27:29 CST 2017
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class symG {
  /* terminals */
  public static final int tkn_procesar = 41;
  public static final int tkn_imprimirK = 46;
  public static final int tkn_caracter = 11;
  public static final int menos = 54;
  public static final int menor = 65;
  public static final int par_der = 48;
  public static final int tkn_terminar = 37;
  public static final int identificador = 4;
  public static final int tkn_defecto = 32;
  public static final int tkn_verdadero = 7;
  public static final int punto = 74;
  public static final int decremento = 71;
  public static final int tkn_cadena = 12;
  public static final int tkn_vacio = 14;
  public static final int tkn_hereda = 20;
  public static final int tkn_llamar = 24;
  public static final int aumento = 70;
  public static final int div = 55;
  public static final int tkn_retornar = 23;
  public static final int menor_igual = 67;
  public static final int tkn_para = 33;
  public static final int tkn_or = 60;
  public static final int tkn_falso = 8;
  public static final int mas = 53;
  public static final int tkn_llamarHK = 27;
  public static final int mayor_igual = 66;
  public static final int decimal = 5;
  public static final int tkn_graphikar = 38;
  public static final int tkn_and = 62;
  public static final int igualacion = 68;
  public static final int tkn_xor = 61;
  public static final int tkn_hacer = 35;
  public static final int tkn_donde = 42;
  public static final int caracter = 6;
  public static final int llave_der = 52;
  public static final int par_izq = 47;
  public static final int cor_der = 50;
  public static final int tkn_privado = 16;
  public static final int tkn_inicio = 25;
  public static final int tkn_decimal = 10;
  public static final int tkn_als = 19;
  public static final int mayor = 64;
  public static final int texto = 3;
  public static final int tkn_dondetodo = 44;
  public static final int tkn_si = 28;
  public static final int tkn_sino = 29;
  public static final int tkn_caso = 31;
  public static final int EOF = 0;
  public static final int tkn_not = 63;
  public static final int tkn_entero = 9;
  public static final int tkn_dondecada = 43;
  public static final int tkn_var = 21;
  public static final int numero = 2;
  public static final int potencia = 56;
  public static final int nombreArchivo = 75;
  public static final int tkn_importar = 18;
  public static final int error = 1;
  public static final int tkn_seleccion = 30;
  public static final int tkn_protegido = 17;
  public static final int diferente = 69;
  public static final int tkn_columna = 40;
  public static final int tkn_bool = 13;
  public static final int llave_izq = 51;
  public static final int por = 57;
  public static final int tkn_imprimir = 45;
  public static final int dosp = 73;
  public static final int coma = 58;
  public static final int igual = 72;
  public static final int cor_izq = 49;
  public static final int tkn_publico = 15;
  public static final int int_der = 59;
  public static final int tkn_incluirHK = 26;
  public static final int tkn_mientras = 34;
  public static final int tkn_nuevo = 22;
  public static final int tkn_datos = 39;
  public static final int tkn_continuar = 36;
}

