
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Mar 17 21:28:04 CST 2017
//----------------------------------------------------

package Analisis;

/** CUP generated class containing symbol constants. */
public class symH {
  /* terminals */
  public static final int tkn_revers = 14;
  public static final int mod = 36;
  public static final int tkn_decc = 9;
  public static final int cor_izq = 29;
  public static final int coma = 38;
  public static final int igual = 51;
  public static final int tkn_and = 41;
  public static final int llave_der = 28;
  public static final int identificador = 4;
  public static final int caracter = 53;
  public static final int tkn_or = 40;
  public static final int tkn_min = 10;
  public static final int igualacion = 47;
  public static final int tkn_if = 21;
  public static final int par_der = 26;
  public static final int tkn_succ = 8;
  public static final int numero = 2;
  public static final int menos = 32;
  public static final int menor = 43;
  public static final int tkn_else = 22;
  public static final int dosp = 52;
  public static final int aumento = 49;
  public static final int EOF = 0;
  public static final int pyc = 46;
  public static final int mayor_igual = 44;
  public static final int mas = 31;
  public static final int error = 1;
  public static final int mayor = 42;
  public static final int tkn_then = 23;
  public static final int tkn_par = 16;
  public static final int dadmiracion = 50;
  public static final int cor_der = 30;
  public static final int por = 35;
  public static final int tkn_asc = 17;
  public static final int menor_igual = 45;
  public static final int potencia = 34;
  public static final int sqrt = 37;
  public static final int tkn_let = 6;
  public static final int tkn_end = 20;
  public static final int tkn_sum = 12;
  public static final int texto = 3;
  public static final int diferente = 48;
  public static final int llave_izq = 27;
  public static final int dolar = 39;
  public static final int tkn_impr = 15;
  public static final int tkn_calcular = 7;
  public static final int tkn_max = 11;
  public static final int tkn_desc = 18;
  public static final int tkn_product = 13;
  public static final int tkn_length = 19;
  public static final int div = 33;
  public static final int tkn_case = 24;
  public static final int decimal = 5;
  public static final int par_izq = 25;
}

